apiVersion: v1
entries:
  kapacitor:
  - apiVersion: v1
    appVersion: 1.6.4
    created: "2025-02-04T12:20:15.069031+05:30"
    description: InfluxDB's native data processing engine. It can process both stream
      and batch data from InfluxDB.
    digest: 00d6afe2783c25264fa99498093b47514da812bfdabfabcb61550fc9b2608843
    home: https://www.influxdata.com/time-series-platform/kapacitor/
    keywords:
    - kapacitor
    - stream
    - etl
    - timeseries
    - influxdb
    - influxdata
    maintainers:
    - email: rawkode@influxdata.com
      name: rawkode
    - email: giacomo@influxdata.com
      name: gitirabassi
    - email: urakiny@gmail.com
      name: aisuko
    name: kapacitor
    sources:
    - https://github.com/influxdata/kapacitor
    urls:
    - https://rafaysystems.github.io/influxdata-helm-charts/charts/kapacitor-1.4.7.tgz
    version: 1.4.7
generated: "2025-02-04T12:20:15.067252+05:30"
